apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenoid

spec:
  replicas: 1

  selector:
    matchLabels:
      app: selenoid

  template:
    metadata:
      labels:
        app: selenoid

    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      containers:
        - name: selenoid
          image: aerokube/selenoid:1.11.3
          imagePullPolicy: IfNotPresent

          env:
            - name: DOCKER_API_VERSION
              value: "1.44"

          args:
            - "-conf"
            - "/etc/selenoid/browsers.json"

          ports:
            - containerPort: 4444

          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock

            - name: selenoid-config
              mountPath: /etc/selenoid
              readOnly: true

      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock

        - name: selenoid-config
          configMap:
            name: selenoid-config

---
apiVersion: v1
kind: Service
metadata:
  name: selenoid

spec:
  selector:
    app: selenoid

  ports:
    - name: http
      protocol: TCP
      port: 4444
      targetPort: 4444
      nodePort: 30444

  type: NodePort