apiBaseUrl = http://localhost:4111
apiVersion = /api/v1

admin.username = admin
admin.password = admin

uiRemote = http://localhost:4444/wd/hub
uiBaseUrl = http://192.168.3.45:3000
browser = chrome
browserSize = 1920x1080

db.url=jdbc:postgresql://localhost:5433/nbank
db.username=postgres
db.password=postgres